### ISSUE TITLE
Why is this repo hosted on Github?

### ISSUE THREAD

**Issue by mimi89999** [nvllsvm/freecyngn#21]
Github servers are running proprietary software. Github is proprietary. You are also required to run proprietary JS code in your browser.

**Comment by mar-v-in** [comment]
Git is a decentral versioning system. This repo is primarily hosted on my personal computer. GitHub just put up an additional host storing the repo on a publicly accessible server and so you can do. Feel free to sync the repo on GitHub and any device you like or meet me in person if you want to transfer directly from the source (my personal computer).

Regarding proprietary JS: Disable JS in your browser. Nobody forces you to execute arbitrary JS blobs on your client. In fact it does not matter that the JS from GitHub is more likely to be proprietary than the JS blob from GitLab. In both cases you're not able to able to tell, because you get a minified blob from a non-trustworthy third-party server - and there is not even a guarantee that it stays the same. So even if you verify a certain blob to be free software, you don't know if the blob you are actually using is free software.

You can always fork this repo to another third party server that you trust more...

**Comment by nvllsvm** [comment]
Won't change. See this Repo's WTFPL license if you have a problem with GitHub.
